In [4]:
import numpy as np

In [7]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

In [9]:
cold = porridge[porridge < 60]
cold

array([50, 56, 51])

In [10]:
hot = porridge[porridge > 80]
hot

array([90, 85, 98])

In [11]:
just_right = porridge[(porridge >= 60) &(porridge <= 80)]
just_right

array([79, 65, 63, 79])